### PR TITLE
Add Jenkinsfile pipeline and templates

### PR DESCRIPTION
**Pull request by csrwng**
Adds pipeline and corresponding templates

### CODE REVIEW

**Comment by jorgemoralespou** [comment]
@csrwng Why is settings.xml file added? It shouldn't be necessary to override default settings.xml and right approach in the enterprise is to use a MAVEN_MIRROR_URL and have a settings.xml able to use that variable. This settings.xml look very much like the one provided by default on both EAP, Wildfly and jorgemoralespou/java-s2i

**Comment by csrwng** [comment]
@jorgemoralespou it is the exact same. In this case, because I am building on the maven slave that ships with our current jenkins image (https://github.com/openshift/jenkins/tree/master/slave-maven), I'm having to include the settings.xml because they're not part of that image.

**Comment by csrwng** [comment]
hmm, now that I'm looking at it, the settings are part of that image as well. I will need to look again and see why my builds were failing.

**Comment by csrwng** [comment]
Removed extra settings file. It turns out I just needed to point to it.

**Pull request merged**
